export default {
  root: {
    height: '50px',
    padding: '0 10px',
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '18px !important',
    boxShadow: 'rgba(0, 0, 0, 0.2) 1px 1px 5px',
  },
  title: {
    fontWeight: '600',
    letterSpacing: '1px',
    color: '#000',
    fontSize: '15px',
  },
  ctaContainer: {
    display: 'flex',
    alignItems: 'center',
  },
  ctaBtn: {
    padding: '0',
    margin: '0 5px',
    WebkitAppearance: 'none',
    border: '1px solid #64CCC9 !important',
    borderRadius: '15px',
    width: '30px',
    height: '30px',
    backgroundColor: '#64CCC9',
    color: '#fff',
    outline: 'none',
    borderColor: '#64CCC9',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chevronIcon: {
    fontSize: '25px',
  },
  selectionIcon: {
    fontSize: '20px',
  },
};
